openapi: 3.0.2
info:
  title: MoldON API V1
  version: 1.0.0
  description: |-
    Moldon API
    - 1. 사업자등록증 OCR
    - 2. 거래처 조회
    - 3. 표준어 카테고리 목록
    - 4. 표준어 목록
    - 5. 유사어 조회
    - ※ 출처: __ 
servers:
  - url: http://ec2-52-79-123-200.ap-northeast-2.compute.amazonaws.com:8090/v1
    description: Production server
security: []
paths:
  /BusinessRegistrationOCR:
    $ref: paths/BusinessRegistrationOCR.yaml
  /GetCompanyInfo:
    $ref: paths/GetCompanyInfo.yaml
  /GetCategories:
    $ref: paths/GetCategories.yaml
  /GetStandardWords:
    $ref: paths/GetStandardWords.yaml
  /GetSimilarWords:
    $ref: paths/GetSimilarWords.yaml
components:
  securitySchemes:
    api-key:
      type: apiKey
      name: api-key
      in: header
